[phases.setup]
  nixPkgs = ['...', 'php83', 'nodejs_20']

[phases.install]
  cmds = ['composer install --no-dev --optimize-autoloader --no-interaction']

[phases.build]
  cmds = [
    'npm ci --foreground-scripts',
    'npm run build',
    'php artisan migrate --force --no-interaction',
    'php artisan db:seed --force --no-interaction || true',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
  ]

[start]
  cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"